### ISSUE TITLE
"save oar" Commands and Errors

### ISSUE THREAD

**Issue by Vinhold** [InWorldz/halcyon#344]
Halcyon currently has three commands to save an oar file:
save oar <oar name> <store_assets> - Save a region's data to an OAR archive
saveexplicit oar <region name> <oar filename> <store_assets> - Save a region's data to an OAR archive
saveportable oar <oar filename> [allowed_uuid allowed_uuid ...] - Save a region's data to an OAR archive with assets suitable for export from inworldz.

These are currently each separate code sections doing almost the same things. Though the "saveportable oar" appears to be only a stub that was never implemented or completed as it does nothing. The other two have a lot of errors resulting in assets not being saved in the oar.
Related issue: Skip UUIDs (that can't be) read from damaged assets #343

I propose these three commands be combined into one process with extended parms:
**<region name>** - deprecated parameter since multiple regions per simulator is not allowed in Halcyon at this time. So it would only be the active region.
**<oar name>** - output file path/name.
**<store_assets>** - flag 1=store assets, 0=not store assets.
**[allowed_uuid allowed_uuid ...]** - I am not sure what this was intended to do, appears to be an allowed asset by UUID list for export to provide a list of content to export with the oar.
**<compatible>** - flag 1=OpenSim output compatibility, 0=Halcyon format

That  way there is support for other grids using the OpenSim format or Halcyon format. 
Currently the errors returned is the same regardless of assets for this command:
save oar MyRegion.oar 1

2017-03-13 08:19:30,196 [ConsoleThread] ERROR OpenSim.Region.Framework.Scenes.UuidGatherer - [ASSET GATHERER]: Failed to get part - System.NullReferenceException: Object reference not set to an instance of an object.
   at OpenSim.Region.Framework.Scenes.UuidGatherer.GatherAssetUuids(SceneObjectGroup sceneObject, IDictionary`2 assetUuids) in X:\halcyon-0.9.32.6272\OpenSim\Region\Framework\Scenes\UuidGatherer.cs:line 117
   at OpenSim.Region.Framework.Scenes.UuidGatherer.GetSceneObjectAssetUuids(UUID sceneObjectUuid, IDictionary`2 assetUuids) in X:\halcyon-0.9.32.6272\OpenSim\Region\Framework\Scenes\UuidGatherer.cs:line 287
   at OpenSim.Region.Framework.Scenes.UuidGatherer.GatherAssetUuids(UUID assetUuid, AssetType assetType, IDictionary`2 assetUuids) in X:\halcyon-0.9.32.6272\OpenSim\Region\Framework\Scenes\UuidGatherer.cs:line 98
   at OpenSim.Region.Framework.Scenes.UuidGatherer.GatherAssetUuids(SceneObjectGroup sceneObject, IDictionary`2 assetUuids) in X:\halcyon-0.9.32.6272\OpenSim\Region\Framework\Scenes\UuidGatherer.cs:line 170
2017-03-13 08:19:30,212 [ConsoleThread] DEBUG OpenSim.Region.Framework.Scenes.UuidGatherer - [ASSET GATHERER]: Texture entry length for prim was 98 (min is 46)
2017-03-13 08:19:30,227 [ConsoleThread] ERROR OpenSim.Region.Framework.Scenes.Serialization.SceneObjectSerializer - [SERIALIZER]: Deserialization of xml failed with System.Xml.XmlException: Data at the root level is invalid. Line 1, position 1.
   at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at System.Xml.XmlDocument.LoadXml(String xml)
   at OpenSim.Region.Framework.Scenes.Serialization.SceneObjectSerializer.FromOriginalXmlFormat(UUID fromUserInventoryItemID, String xmlData) in X:\halcyon-0.9.32.6272\OpenSim\Region\Framework\Scenes\Serialization\SceneObjectSerializer.cs:line 139.  xml was ITG

**Comment by appurist** [comment]
This issue covers at least four fairly separate topics, so they should probably be four issues, but I have some concerns with each.  

The first is that the exceptions are just bugs that need to be fixed. I've addressed the null reference exception, but if invalid XML can generate other exceptions, whether we need to catch those (or not?) is really a separate topic like #343. In that regard, I'm not really sure it's a good idea to skip assets that don't match our expected format, as that means any resulting OAR file will not be a complete backup.  Perhaps that should be left to the person or process invoking the command, with an extra parameter indicating whether failure to fetch an asset is fatal for OAR creation or whether it should continue on errors and save as much as it can.  For region backups, we're going to want to know the backup failed, not have it silently continue, possibly without _any_ objects in the backup.

The next problem is that these commands are referenced by different automated processes, and merging into a single command cannot be done in a backwards-compatible manner.  I haven't looked at the calling code for a while, but if it has copied sections of code that do the same thing, obviously we can factor that code into a common implementation. However, I suspect there may be differences that aren't apparent, that don't factor well.

Adding support for exporting in an OpenSim compatible format is no really considered an important goal, as migrations tend to be entirely in the other direction.  There is already too much work on the table and not enough developer resources, so there is no possibility that I would be able to have a chance to add support for OpenSim OAR exports here, although other Halcyon developers might choose to do so, and I would support that.  However, it would need to be done as a non-disruptive, backwards-compatible addition.

And finally, moving the OAR export command to an external process is something that I think we could do, but like the topic above, I don't think it's going to make it on the priority radar any time within the foreseeable future.  It wouldn't really need any coordination with the region, just access to the database storage for the region and possibly assets.  It could be temporally-inconsistent, e.g. if over the course of some time period representing the OAR backup time, a region deleted object A and created object B, I think it's theoretically possible that the backup could have neither, or both, depending on the database indexing.  But that wouldn't be so bad, since during the period of the backup, one, both, or neither existed in the region.

**Comment by kf6kjg** [comment]
@appurist Was any of this resolved by your OAR fixes for the InWorldz shutdown?

**Comment by Vinhold** [comment]
The OAR save and load processing are region command processes, as such are seen as Region simulator actions. I agree this could be put to some external command processor, which might be called from a website with appropriate filtering applied for what gets put in the file. Most of the OAR files issues I seem to be encountering are related to OpenSim content originally loaded OK, but wont save again back to an OAR without a load of errors. Errors generally are XML invalid structure errors I am seeing. It would be OK with me to have these taken as separate issues however that would make them more focused points / problems for correction. I have a collection of problems I am running into for saving an OAR, and loading an OAR. Some of these may also affect the InWorldz OARs saved and to be reloaded.
