### ISSUE TITLE
Halcyon startup crash

### ISSUE THREAD

**Issue by QuillLittlefeather** [InWorldz/halcyon#363]
Getting this error 

2017-04-07 13:40:20,363 [1] INFO  OpenSim.Application - [HALCYON MAIN]: configured log4net using default Halcyon.exe.config
2017-04-07 13:40:20,394 [1] INFO  OpenSim.Application - Performing compatibility checks... 
2017-04-07 13:40:20,410 [1] INFO  OpenSim.Application - Environment is compatible.

2017-04-07 13:40:20,441 [ConsoleThread] INFO  OpenSim.ConfigurationLoader - [CONFIG] Reading configuration settings
2017-04-07 13:40:20,441 [ConsoleThread] INFO  OpenSim.ConfigurationLoader - [CONFIG] Reading configuration file C:\Users\Administrator\Downloads\halcyon-dev\halcyon-dev\bin\Halcyon.ini
2017-04-07 13:40:20,519 [ConsoleThread] INFO  OpenSim.Framework.Servers.BaseOpenSimServer - [STARTUP]: Beginning startup processing
2017-04-07 13:40:20,551 [ConsoleThread] INFO  OpenSim.OpenSim - ====================================================================
2017-04-07 13:40:20,551 [ConsoleThread] INFO  OpenSim.OpenSim - ========================= STARTING HALCYON =========================
2017-04-07 13:40:20,551 [ConsoleThread] INFO  OpenSim.OpenSim - ====================================================================
2017-04-07 13:40:20,551 [ConsoleThread] INFO  OpenSim.OpenSim - [HALCYON MAIN]: Running in grid mode
2017-04-07 13:40:20,551 [ConsoleThread] INFO  OpenSim.OpenSim - GC: Server mode: False, Interactive
2017-04-07 13:40:20,582 [ConsoleThread] INFO  OpenSim.Region.Framework.StorageManager - [DATASTORE]: Attempting to load OpenSim.Data.MySQL.dll
2017-04-07 13:40:20,598 [ConsoleThread] INFO  OpenSim.Region.Framework.StorageManager - [DATASTORE]: Added IRegionDataStore Interface
2017-04-07 13:40:20,598 [ConsoleThread] INFO  OpenSim.Region.ClientStack.ClientStackManager - [CLIENTSTACK]: Attempting to load OpenSim.Region.ClientStack.LindenUDP.dll
2017-04-07 13:40:20,644 [ConsoleThread] INFO  OpenSim.Region.ClientStack.ClientStackManager - [CLIENTSTACK]: Added IClientNetworkServer Interface
2017-04-07 13:40:20,644 [ConsoleThread] DEBUG OpenSim.OpenSimBase - [HALCYONBASE] Attempting to load asset server id=WHIP
2017-04-07 13:40:20,660 [ConsoleThread] INFO  OpenSim.Framework.PluginLoader`1 - [PLUGINS]: Initializing addin manager
2017-04-07 13:40:20,785 [ConsoleThread] INFO  OpenSim.Framework.PluginLoader`1 - [PLUGINS]: Loading extension point /OpenSim/AssetClient
2017-04-07 13:40:20,801 [ConsoleThread] ERROR OpenSim.Application - [APPLICATION]: 
APPLICATION EXCEPTION DETECTED: System.UnhandledExceptionEventArgs

Exception: System.Exception: Asset server WHIP could not be loaded
   at OpenSim.OpenSimBase.InitializeAssetCache() in C:\Users\Administrator\Downloads\halcyon-dev\halcyon-dev\OpenSim\Base\OpenSimBase.cs:line 324
   at OpenSim.OpenSimBase.Initialize() in C:\Users\Administrator\Downloads\halcyon-dev\halcyon-dev\OpenSim\Base\OpenSimBase.cs:line 286
   at OpenSim.Region.ClientStack.RegionApplicationBase.StartupSpecific() in C:\Users\Administrator\Downloads\halcyon-dev\halcyon-dev\OpenSim\Region\ClientStack\RegionApplicationBase.cs:line 107
   at OpenSim.OpenSimBase.StartupSpecific() in C:\Users\Administrator\Downloads\halcyon-dev\halcyon-dev\OpenSim\Base\OpenSimBase.cs:line 201
   at OpenSim.OpenSim.StartupSpecific() in C:\Users\Administrator\Downloads\halcyon-dev\halcyon-dev\OpenSim\Base\OpenSim.cs:line 163
   at OpenSim.Framework.Servers.BaseOpenSimServer.Startup() in C:\Users\Administrator\Downloads\halcyon-dev\halcyon-dev\OpenSim\Framework\Servers\BaseOpenSimServer.cs:line 300
   at OpenSim.Application.Main(String[] args) in C:\Users\Administrator\Downloads\halcyon-dev\halcyon-dev\InWorldz\Halcyon\Application.cs:line 145

Application is terminating: True

Every thing in uni is correct and the compile worked just fine.
What is the issue

**Comment by appurist** [comment]
I'm just heading out for errands, but I saw this report and wanted to give you at least a quick answer. It looks like you haven't started the WHIP asset server yet. Look for the `whip.exe` and `whip.cfg` files. I can help more when I return.

**Comment by QuillLittlefeather** [comment]
All Programs whip apeture and grid servers running however can not start halcyon.exe in grid mode or standalone.

**Comment by QuillLittlefeather** [comment]
Here is the uni for halycon

https://pastebin.com/UvysMxz2

**Comment by mdickson** [comment]
Download the last distribution release (zip file) unzip it over what you built.  Then clean and rebuild the tree.  I'm pretty sure there is a binary missing from the source checkout that causes this issue when you build from sources only.

**Comment by QuillLittlefeather** [comment]
I built from the zip under releases

**Comment by QuillLittlefeather** [comment]
rebuilding did not help same error why can't you post a prebuilt version if it's a compiling issue.

And I know whip is running as apeture is connected to it.

**Comment by mdickson** [comment]
Quill then take a look at the thread marked [https://github.com/InWorldz/halcyon/issues/318](url). It may be relevant.

**Comment by QuillLittlefeather** [comment]
Ok thank you had to unblock using powershell
